services:
  mongo:
    image: mongo:latest # Use the official MongoDB image
    container_name: mongodb_container # Optional: give your container a specific name
    ports:
      - "27017:27017" # Map host port 27017 to container port 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: maestro
      MONGO_INITDB_ROOT_PASSWORD: x47giKHY
    volumes:
      - mongo_data:/data/db # Persist data to a named volume

volumes:
  mongo_data:
    driver: local